#!/bin/bash
#
# Service Report Generator - 自动化服务报告生成工具
# 
# 使用方法:
#   ./service-report.sh generate --type project --title "Title" --output file.md
#   ./service-report.sh weekly --week 2026-W10 --output weekly.md
#   ./service-report.sh service --service "API" --status healthy --output service.md
#   ./service-report.sh template --name monthly --vars "month=March,year=2026"
#   ./service-report.sh list-templates
#   ./service-report.sh cron --schedule "cron" --type weekly
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/templates"
OUTPUT_DIR="${OUTPUT_DIR:-$SCRIPT_DIR/output}"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 创建必要目录
mkdir -p "$TEMPLATE_DIR" "$OUTPUT_DIR"

# 默认值
OUTPUT_FORMAT="markdown"
REPORT_TITLE=""
REPORT_DATE=$(date +"%Y-%m-%d %H:%M:%S")
REPORT_TYPE="general"

# 帮助信息
show_help() {
    cat << EOF
Service Report Generator - 自动化服务报告生成工具

使用方法:
    $(basename $0) <command> [options]

命令:
    generate, gen         生成通用报告
    weekly, w             生成周报
    monthly, m            生成月报
    service, s           生成服务报告
    project, p           生成项目报告
    template, t          使用模板生成报告
    list-templates, lt   列出可用模板
    alert, a             生成告警报告
    cron                 设置定时任务
    help, h              显示帮助信息

选项:
    --type, -t           报告类型 (project/weekly/monthly/service/alert)
    --title, -T          报告标题
    --output, -o         输出文件路径
    --format, -f         输出格式 (markdown/html/json)
    --service, -s        服务名称
    --status             服务状态 (healthy/degraded/down)
    --severity           告警级别 (info/warning/critical)
    --week               周编号 (如 2026-W10)
    --month              月份 (如 March)
    --year               年份 (如 2026)
    --vars               变量列表 (key1=value1,key2=value2)
    --schedule           Cron 表达式

示例:
    $(basename $0) generate --type project --title "Q1 System Upgrade" -o report.md
    $(basename $0) weekly --week 2026-W10 -o weekly.md
    $(basename $0) service --service "API Gateway" --status healthy -o service.md
    $(basename $0) template --name monthly --vars "month=March,year=2026"
    $(basename $0) list-templates

EOF
}

# 解析变量字符串
parse_vars() {
    local vars="$1"
    IFS=',' read -ra VAR_ARRAY <<< "$vars"
    for var in "${VAR_ARRAY[@]}"; do
        key=$(echo "$var" | cut -d'=' -f1)
        value=$(echo "$var" | cut -d'=' -f2-)
        export "VAR_$key=$value"
    done
}

# 替换模板变量
replace_vars() {
    local content="$1"
    content="${content//\{\{title\}\}/$REPORT_TITLE}"
    content="${content//\{\{date\}\}/$REPORT_DATE}"
    content="${content//\{\{service\}\}/$SERVICE_NAME}"
    content="${content//\{\{status\}\}/$SERVICE_STATUS}"
    content="${content//\{\{month\}\}/${VAR_month:-$(date +%B)}}"
    content="${content//\{\{year\}\}/${VAR_year:-$(date +%Y)}}"
    content="${content//\{\{week\}\}/${VAR_week:-$(date +%V)}}"
    echo "$content"
}

# 生成周报
generate_weekly_report() {
    local week="${VAR_week:-$(date +%V)}"
    local year="${VAR_year:-$(date +%Y)}"
    
    cat << EOF
# 周报 - $year 第${week}周

**生成日期**: $REPORT_DATE

## 📋 本周完成事项

- [ ] 任务 1
- [ ] 任务 2
- [ ] 任务 3

## 🚧 进行中事项

- [ ] 项目 A - 进行中
- [ ] 项目 B - 待开始

## ❌ 遇到的问题

| 问题 | 状态 | 负责人 |
|------|------|--------|
| 问题 1 | 已解决 | - |
| 问题 2 | 处理中 | - |

## 📅 下周计划

- [ ] 计划任务 1
- [ ] 计划任务 2
- [ ] 计划任务 3

## 📊 关键指标

| 指标 | 本周 | 变化 |
|------|------|------|
|完成任务| 5 | +2 |
|代码提交| 12 | +3 |
|会议时长| 8h | -1h |

---
*Generated by Service Report Generator*
EOF
}

# 生成月报
generate_monthly_report() {
    local month="${VAR_month:-$(date +%B)}"
    local year="${VAR_year:-$(date +%Y)}"
    
    cat << EOF
# 月报 - $month $year

**生成日期**: $REPORT_DATE

## 📈 月度概览

本月整体进展**顺利**，完成预期目标的 85%。

### 关键成就

1. ✅ 完成了系统架构升级
2. ✅ 团队扩展至 5 人
3. ✅ 客户满意度提升至 95%

## 📊 关键指标

| 指标 | 目标 | 实际 | 完成率 |
|------|------|------|--------|
| 收入 | 100K | 95K | 95% |
| 新增用户 | 500 | 520 | 104% |
| 活跃度 | 80% | 78% | 97.5% |

## 🎯 成就与亮点

- **技术突破**: 实现了自动化部署流程，部署时间减少 60%
- **团队成长**: 新成员全部通过试用期
- **客户反馈**: 收到 3 个重要客户的积极反馈

## 📝 改进建议

1. 加强跨团队协作
2. 优化资源分配
3. 完善文档体系

## 🎯 下月目标

- [ ] 完成产品 v2.0 发布
- [ ] 扩展至新市场
- [ ] 提升系统性能 20%

---
*Generated by Service Report Generator*
EOF
}

# 生成服务报告
generate_service_report() {
    local service="${SERVICE_NAME:-Unknown Service}"
    local status="${SERVICE_STATUS:-unknown}"
    
    # 状态颜色
    local status_icon="⚪"
    local status_text="未知"
    case "$status" in
        healthy)
            status_icon="✅"
            status_text="健康"
            ;;
        degraded)
            status_icon="⚠️"
            status_text="降级"
            ;;
        down)
            status_icon="❌"
            status_text="宕机"
            ;;
    esac
    
    cat << EOF
# 服务状态报告 - $service

**生成日期**: $REPORT_DATE

## 服务概览

| 项目 | 详情 |
|------|------|
| 服务名称 | $service |
| 状态 | $status_icon $status |
| 版本 | v1.0.0 |
| 运行环境 | Production |

## 📊 运行指标

| 指标 | 当前值 | 阈值 | 状态 |
|------|--------|------|------|
| 可用性 | 99.95% | 99.9% | ✅ |
| 响应时间 | 120ms | 200ms | ✅ |
| 错误率 | 0.02% | 0.1% | ✅ |
| CPU 使用率 | 45% | 80% | ✅ |
| 内存使用率 | 62% | 85% | ✅ |

## 📋 事件记录

### 最近事件 (24小时内)

| 时间 | 事件 | 级别 | 状态 |
|------|------|------|------|
| $(date -d "12 hours ago" +"%Y-%m-%d %H:%M" 2>/dev/null || echo "N/A") | 健康检查通过 | Info | ✅ |
| $(date -d "1 day ago" +"%Y-%m-%d %H:%M" 2>/dev/null || echo "N/A") | 部署完成 | Info | ✅ |

## 🔧 维护信息

- **下次维护窗口**: 每周日 2:00-4:00
- **最后部署**: $(date -d "2 days ago" +"%Y-%m-%d" 2>/dev/null || echo "N/A")
- **部署频率**: 每周 2 次

## 📞 联系方式

- **值班团队**: oncall@example.com
- **紧急电话**: +86-xxx-xxxx-xxxx

---
*Generated by Service Report Generator*
EOF
}

# 生成项目报告
generate_project_report() {
    local title="${REPORT_TITLE:-项目报告}"
    
    cat << EOF
# 项目报告 - $title

**生成日期**: $REPORT_DATE

## 📋 项目概述

本报告用于跟踪项目进度和状态。

### 项目信息

| 项目 | 详情 |
|------|------|
| 项目名称 | $title |
| 状态 | 进行中 |
| 负责人 | - |
| 开始日期 | - |
| 目标完成日期 | - |

## 🎯 里程碑

| 里程碑 | 计划日期 | 实际日期 | 状态 |
|--------|----------|----------|------|
| 需求分析 | - | - | ✅ |
| 设计完成 | - | - | ✅ |
| 开发完成 | - | - | 🔄 |
| 测试完成 | - | - | ⏳ |
| 上线发布 | - | - | ⏳ |

## 👥 团队成员

| 角色 | 姓名 | 职责 |
|------|------|------|
| 负责人 | - | 项目管理 |
| 开发 | - | 核心开发 |
| 测试 | - | 质量保证 |
| 设计 | - | UI/UX |

## ⚠️ 风险评估

| 风险 | 影响 | 概率 | 应对措施 |
|------|------|------|----------|
| 风险 1 | 高 | 中 | 措施描述 |
| 风险 2 | 中 | 低 | 措施描述 |

## 📅 后续计划

1. 继续开发核心功能
2. 进行内部测试
3. 准备上线部署

---
*Generated by Service Report Generator*
EOF
}

# 生成告警报告
generate_alert_report() {
    local severity="${VAR_severity:-info}"
    local service="${SERVICE_NAME:-Unknown}"
    
    local severity_icon="ℹ️"
    case "$severity" in
        critical) severity_icon="🔴" ;;
        warning) severity_icon="🟡" ;;
        info) severity_icon="🔵" ;;
    esac
    
    cat << EOF
# 告警报告 - $service

**生成日期**: $REPORT_DATE

## 告警信息

| 项目 | 详情 |
|------|------|
| 严重级别 | $severity_icon $severity |
| 服务 | $service |
| 触发时间 | $REPORT_DATE |

## 📋 事件详情

**告警描述**: 

**影响范围**: 

**持续时间**: 

## 🔧 处理措施

1. 
2. 
3. 

## 📝 后续行动

- [ ] 根本原因分析
- [ ] 制定预防措施
- [ ] 更新监控规则

---
*Generated by Service Report Generator*
EOF
}

# 列出模板
list_templates() {
    echo "可用模板:"
    echo ""
    echo "  project     - 项目报告模板"
    echo "  weekly      - 周报模板"
    echo "  monthly     - 月报模板"
    echo "  service     - 服务报告模板"
    echo "  alert       - 告警报告模板"
    echo "  general     - 通用报告模板"
    echo ""
    echo "使用示例:"
    echo "  $(basename $0) template --name monthly --vars \"month=March,year=2026\" -o report.md"
}

# 主函数
main() {
    local command="${1:-help}"
    shift || true
    
    # 解析全局选项
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --title|-T)
                REPORT_TITLE="$2"
                shift 2
                ;;
            --output|-o)
                OUTPUT_FILE="$2"
                shift 2
                ;;
            --format|-f)
                OUTPUT_FORMAT="$2"
                shift 2
                ;;
            --service|-s)
                SERVICE_NAME="$2"
                shift 2
                ;;
            --status)
                SERVICE_STATUS="$2"
                shift 2
                ;;
            --severity)
                VAR_severity="$2"
                shift 2
                ;;
            --week)
                VAR_week="$2"
                shift 2
                ;;
            --month)
                VAR_month="$2"
                shift 2
                ;;
            --year)
                VAR_year="$2"
                shift 2
                ;;
            --vars)
                parse_vars "$2"
                shift 2
                ;;
            --type|-t)
                REPORT_TYPE="$2"
                shift 2
                ;;
            --schedule)
                CRON_SCHEDULE="$2"
                shift 2
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "未知选项: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # 执行命令
    case "$command" in
        generate|gen)
            case "$REPORT_TYPE" in
                project) generate_project_report ;;
                weekly) generate_weekly_report ;;
                monthly) generate_monthly_report ;;
                service) generate_service_report ;;
                alert) generate_alert_report ;;
                *) generate_project_report ;;
            esac
            ;;
        weekly|w)
            generate_weekly_report
            ;;
        monthly|m)
            generate_monthly_report
            ;;
        service|s)
            generate_service_report
            ;;
        project|p)
            generate_project_report
            ;;
        template|t)
            case "$REPORT_TYPE" in
                monthly) generate_monthly_report ;;
                weekly) generate_weekly_report ;;
                service) generate_service_report ;;
                project) generate_project_report ;;
                alert) generate_alert_report ;;
                *) generate_project_report ;;
            esac
            ;;
        list-templates|lt)
            list_templates
            exit 0
            ;;
        alert|a)
            generate_alert_report
            ;;
        cron)
            if [[ -z "$CRON_SCHEDULE" ]]; then
                log_error "请指定 --schedule 参数"
                exit 1
            fi
            log_info "创建定时任务: $CRON_SCHEDULE"
            echo "# 定时报告任务
# 添加以下行到 crontab:
# $CRON_SCHEDULE $SCRIPT_DIR/\$(basename \$0) weekly -o ~/reports/weekly-\$(date +\%Y-\%W).md"
            ;;
        help|h)
            show_help
            exit 0
            ;;
        *)
            log_error "未知命令: $command"
            show_help
            exit 1
            ;;
    esac
    
    # 输出到文件
    if [[ -n "$OUTPUT_FILE" ]]; then
        if [[ -d "$OUTPUT_FILE" ]]; then
            OUTPUT_FILE="$OUTPUT_DIR/$(basename "${REPORT_TITLE:-report}" 2>/dev/null || echo "report").md"
        fi
        log_success "报告已保存到: $OUTPUT_FILE"
    fi
}

# 如果没有参数，显示帮助
if [[ $# -eq 0 ]]; then
    show_help
    exit 0
fi

main "$@"
