#!/bin/bash
# ========================================
# Resume Generator - 技术简历自动生成工具
# ========================================

set -e

# 配置
TEMPLATE_DIR="${TEMPLATE_DIR:-$HOME/.openclaw/templates/resume}"
CONFIG_FILE="${CONFIG_FILE:-$HOME/.openclaw/config/resume.yaml}"
OUTPUT_DIR="${OUTPUT_DIR:-.}"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 日志函数
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 帮助信息
show_help() {
    cat << EOF
Resume Generator - 技术简历自动生成工具

用法: $(basename $0) [选项]

选项:
    -t, --template <name>   指定模板 (tech/devops/product/minimal)
    -f, --format <format>   输出格式 (markdown/pdf/html)
    -o, --output <file>     输出文件
    -p, --projects          包含 GitHub 项目经验
    -c, --config <file>     配置文件路径
    -h, --help              显示帮助信息

示例:
    $(basename $0) -t devops -f pdf -o resume.pdf
    $(basename $0) --template tech --projects
    $(basename $0) -f markdown -o my-resume.md

EOF
}

# 解析参数
TEMPLATE="tech"
FORMAT="markdown"
OUTPUT=""
INCLUDE_PROJECTS=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--template)
            TEMPLATE="$2"
            shift 2
            ;;
        -f|--format)
            FORMAT="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT="$2"
            shift 2
            ;;
        -p|--projects)
            INCLUDE_PROJECTS=true
            shift
            ;;
        -c|--config)
            CONFIG_FILE="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            log_error "未知选项: $1"
            show_help
            exit 1
            ;;
    esac
done

# 生成简历头部
generate_header() {
    local name="$1"
    local title="$2"
    local email="$3"
    local github="$4"
    local linkedin="$5"
    
    cat << EOF
# $name | $title

📧 $email | 🔗 github.com/$github | 🔗 linkedin.com/in/$linkedin

EOF
}

# 生成技术技能部分
generate_skills() {
    local skills=("$@")
    
    cat << EOF
## 技术技能

EOF
    for skill in "${skills[@]}"; do
        echo "- $skill"
    done
    echo
}

# 生成项目经验
generate_projects() {
    cat << 'EOF'
## 项目经验

### 自动化运维平台
- 基于 Ansible + Terraform 的基础设施即代码
- 将部署时间缩短 70%
- 技术栈: Python, Docker, Kubernetes, AWS

### 监控系统重构
- 搭建 Prometheus + Grafana 监控体系
- 实现全链路追踪
- 告警响应时间提升 50%

### CI/CD 流水线优化
- 使用 GitHub Actions 实现自动化部署
- 部署频率从每周 1 次提升到每日 5 次
- 回滚时间从 30 分钟缩短到 2 分钟

EOF
}

# 生成工作经历
generate_experience() {
    cat << 'EOF'
## 工作经历

### 高级 DevOps 工程师 @ ABC 公司 | 2021 - 至今
- 负责公司级 CI/CD 平台建设
- 主导容器化改造，迁移 50+ 服务到 Kubernetes
- 建立 SRE 体系，SLO 达到 99.9%

### DevOps 工程师 @ XYZ 科技 | 2019 - 2021
- 搭建自动化运维平台
- 实现全链路监控和告警
- 优化 Jenkins 流水线，效率提升 40%

EOF
}

# 主函数
main() {
    log_info "Resume Generator 启动中..."
    
    # 读取配置或使用默认值
    local name="${RESUME_NAME:-张三}"
    local title="${RESUME_TITLE:-Senior DevOps Engineer}"
    local email="${RESUME_EMAIL:-dev@example.com}"
    local github="${RESUME_GITHUB:-your-username}"
    local linkedin="${RESUME_LINKEDIN:-your-username}"
    
    # 技能列表
    local skills=("Cloud: AWS, GCP, Azure" "Container: Docker, Kubernetes" "CI/CD: GitHub Actions, Jenkins" "IaC: Terraform, Ansible" "Monitoring: Prometheus, Grafana" "Script: Python, Bash, Go")
    
    # 生成简历
    {
        generate_header "$name" "$title" "$email" "$github" "$linkedin"
        generate_skills "${skills[@]}"
        
        if [ "$INCLUDE_PROJECTS" = true ]; then
            generate_projects
        fi
        
        generate_experience
        
        echo "---"
        echo "*Generated by Resume Generator Skill*"
    } > "${OUTPUT:-resume.md}"
    
    log_info "简历已生成: ${OUTPUT:-resume.md}"
    
    # 如果需要 PDF 格式
    if [ "$FORMAT" = "pdf" ]; then
        if command -v pandoc &> /dev/null; then
            log_info "正在转换为 PDF..."
            pandoc "${OUTPUT:-resume.md}" -o "${OUTPUT%.md}.pdf"
            log_info "PDF 已生成: ${OUTPUT%.md}.pdf"
        else
            log_warn "pandoc 未安装，请手动转换: pandoc resume.md -o resume.pdf"
        fi
    fi
    
    log_info "完成! ✨"
}

# 执行主函数
main "$@"
